services:
  connect-api:
    image: 1password/connect-api:latest
    ports:
      - "8080:8080"
    volumes:
      - ./1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - connect-data:/home/opuser/.op/data
    environment:
      - OP_SESSION=/home/opuser/.op/1password-credentials.json
      - OP_HTTP_PORT=8080
      - OP_LOG_LEVEL=info

  connect-sync:
    image: 1password/connect-sync:latest
    volumes:
      - ./1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - connect-data:/home/opuser/.op/data
    environment:
      - OP_SESSION=/home/opuser/.op/1password-credentials.json
      - OP_LOG_LEVEL=info

volumes:
  connect-data: